#ifndef INTERPRETER_TOKEN_H
#define INTERPRETER_TOKEN_H

typedef enum {
    // Single character tokens.
    TOKEN_COMMA,
    TOKEN_DOT,
    TOKEN_LEFT_BRACE, TOKEN_RIGHT_BRACE,
    TOKEN_LEFT_PAREN, TOKEN_RIGHT_PAREN,
    TOKEN_LEFT_SQUARE_BRACKET, TOKEN_RIGHT_SQUARE_BRACKET,
    TOKEN_SEMICOLON,

    // Single or double character tokens.
    TOKEN_AMPERSAND, TOKEN_AMPERSAND_AMPERSAND, TOKEN_AMPERSAND_EQUAL,
    TOKEN_BANG, TOKEN_BANG_EQUAL,
    TOKEN_CARET, TOKEN_CARET_CARET, TOKEN_CARET_EQUAL,
    TOKEN_COLON, TOKEN_COLON_COLON,
    TOKEN_EQUAL, TOKEN_EQUAL_EQUAL,
    TOKEN_GREATER, TOKEN_GREATER_EQUAL,
    TOKEN_LESS, TOKEN_LESS_EQUAL,
    TOKEN_MINUS, TOKEN_MINUS_GREATER, TOKEN_MINUS_EQUAL,
    TOKEN_PLUS, TOKEN_PLUS_EQUAL,
    TOKEN_STAR, TOKEN_STAR_EQUAL,
    TOKEN_SLASH, TOKEN_SLASH_EQUAL,
    TOKEN_PIPE, TOKEN_PIPE_PIPE,
    TOKEN_PERCENT, TOKEN_PERCENT_EQUAL,

    // Literals.
    TOKEN_CHAR,
    TOKEN_IDENTIFIER,
    TOKEN_NUMBER,
    TOKEN_STRING,

    // Keywords.
    TOKEN_AS,
    TOKEN_CONST,
    TOKEN_ELSE,
    TOKEN_ENUM,
    TOKEN_FALSE,
    TOKEN_FN,
    TOKEN_IF,
    TOKEN_IMPL,
    TOKEN_LET,
    TOKEN_RETURN,
    TOKEN_STATIC,
    TOKEN_STRUCT,
    TOKEN_TRUE,
    TOKEN_WHILE,

    // Error tokens.
    TOKEN_UNEXPECTED_CHARACTER,
    TOKEN_UNTERMINATED_CHAR_ERROR,
    TOKEN_UNTERMINATED_STRING_ERROR,
    TOKEN_UTF8_ERROR,
    TOKEN_UTF8_ERROR_IN_CHAR,
    TOKEN_UTF8_ERROR_IN_NUMBER,
    TOKEN_UTF8_ERROR_IN_STRING,

    // End of input.
    TOKEN_EOF,
} TokenKind;

typedef struct {
    TokenKind kind;
    size_t start;
    size_t len;

    size_t line;
    size_t column;
} Token;

#endif
